services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda,dynamodb,eventbridge,opensearch,elasticache
      - DEBUG=1

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
